### ISSUE TITLE
Typo: Adding a bill amount label

### ISSUE THREAD

**Issue by MichaelMeinberg** [MakeSchool-Tutorials/Tip-Calculator-Swift#12]
Number 6 says "to to"

_"Change the align center x to to -50 (make sure to hit - twice)."_

**Comment by MichaelMeinberg** [comment]
I am not sure what this sentence wants us to do, set x to -50?   Hit what twice?
(I am not able to see the videos, so maybe watching the videos would make this clearer.)

**Comment by dionlarson** [comment]
Reshot all videos with new constraints (using stackview). Rewrite coming soon.
