### ISSUE TITLE
Creating a project: minor Image-Instruction inconsistency

### ISSUE THREAD

**Issue by szilardinho** [MakeSchool-Tutorials/Tip-Calculator-Swift#16]
Not a huge deal, but under instruction number 8, it states to "Leave Use Core Data and the other two boxes regarding tests unchecked" however the image directly afterwards clearly has all three boxes checked.

This might confuse students who are visual learners and/or don't read instructions (lol)

**Comment by dionlarson** [comment]
Fixed in rewrite. Reshot all videos with new constraints (using stackview). Rewrite coming soon.
