### ISSUE TITLE
Typos in section: Adding a bill amount label

### ISSUE THREAD

**Issue by nikolasburk** [MakeSchool-Tutorials/Tip-Calculator-Swift#17]
In the written instructions 12. to 17., the constraints for the `UITextField` should be set. However, the instructions repeatedly refer to **label** instead of **text field**.

**Comment by nikolasburk** [comment]
Instructions 17. says to pin the **height** when really the **width** to 75.0 (also I think it's worth adding that it's the height of the **text field** again)

**Comment by dionlarson** [comment]
Reshot all videos with new constraints (using stackview). Rewrite coming soon.
