### ISSUE TITLE
Resolve Auto Layout - Explain difference between the section above line and below?

### ISSUE THREAD

**Issue by MichaelMeinberg** [MakeSchool-Tutorials/Tip-Calculator-Swift#18]
Should we explain that the section above the line affects only the object that is selected, while the section below affects all items in the view controller?   

Should we explain that if they add some constraints and it is not working correctly, that they can select "Clear Constraints" to start over (again, make sure they do that with the one above the line, or it will clear all constraints)

**Comment by dionlarson** [comment]
Reshot all videos with new constraints (using stackview). Rewrite coming soon.
