### ISSUE TITLE
Adding a bill amount label step 6

### ISSUE THREAD

**Issue by soggybag** [MakeSchool-Tutorials/Tip-Calculator-Swift#21]
Might be good to mention the name of field to edit here.

**Comment by soggybag** [comment]
Step 7 reads: 

Right-click and drag from the label to the Tip Calculator label and select Top.

Should this say "vertical" instead of "Top"?

**Comment by soggybag** [comment]
This tutorial is about creating a user interface, it would be good to show an image of the user interface at the beginning. This would give students a visual reference to shoot for. I feel this would help students make sense of the steps they are executing.

**Comment by soggybag** [comment]
Step 9 reads: 

Click on the label again and update frame.

I feel this should read something like: 

Click Resolve Auto Layout issues and choose Update Frames.

**Comment by soggybag** [comment]
Undoing the auto-constraints step 1. 

This step seems to ask students to select each constraint and delete manually. This seems problematic as selecting constraints is fiddly and a student might miss a constraint. Might be better to have students select the objects and choose Clear Constraint from the Resolve Auto Layout Issues menu.

**Comment by soggybag** [comment]
In the first paragraph under the "Adding Assets to an App" heading there is a broken img. This is the image of Images.xcassets I'm assuming from the text.

**Comment by soggybag** [comment]
There seems to be a step missing in the section: "Update the styles" The paragraph reads: 

Download the art pack for this tutorial. Unzip the downloaded art pack (by double-clicking the downloaded folder), **and click the small + icon at the bottom of the list** that has only AppIcon in it. Select Import from the pop-up menu. Select the unzipped art folder and bam!

After unzipping students will be in the Finder. The action "...and click the + icon..." is not clear where students will find the + button.

**Comment by soggybag** [comment]
The images in the logo zip are all the same size. Seems they should be different sizes. A student that notices that the images are all the same size will be very confused, especially if they felt confident that they understood that the @2x meant the image should be double resolution.

**Comment by dionlarson** [comment]
All should have been handled in rewrite
