### ISSUE TITLE
Change background color of view?

### ISSUE THREAD

**Issue by MichaelMeinberg** [MakeSchool-Tutorials/Tip-Calculator-Swift#22]
It makes it easier to see the text fields if you do that -
![screen shot 2016-06-10 at 10 11 57 am](https://cloud.githubusercontent.com/assets/4966291/15972523/cbd8f81c-2ef3-11e6-9b2d-362fafa88e7c.png)

**Comment by dionlarson** [comment]
Reshot all videos with new constraints (using stackview). Rewrite coming soon.

It's a bit easier in stackviews to see what is going on.
