### ISSUE TITLE
5. Tip it up! - Change sender "AnyObject" for IBActions?

### ISSUE THREAD

**Issue by MichaelMeinberg** [MakeSchool-Tutorials/Tip-Calculator-Swift#24]
Why Apple hasn't fixed this is beyond me, but should we get them into the habit of changing the sender type to the object type, rather then "AnyObject"?   I think that is considered best practice.

**Comment by MichaelMeinberg** [comment]
Ah, I see why you didn't do it here, because two different type fields are going to call the same routine.

**Comment by dionlarson** [comment]
👍
