### ISSUE TITLE
5. Tip it up! (Adding the logic) - Should we put "self" in front of the variables?

### ISSUE THREAD

**Issue by MichaelMeinberg** [MakeSchool-Tutorials/Tip-Calculator-Swift#25]

**Comment by danielhaaser** [comment]
I think it's somewhat accepted that in Swift, you should only use `self` when necessary, and it isn't in this case when referring to properties. See this style guide: https://github.com/raywenderlich/swift-style-guide#use-of-self

**Comment by MichaelMeinberg** [comment]
Intersting.  I disagree with Ray on this, however.  But this maybe a "_tab vs spaces"_argument.
The reason I like adding "self" is it tells anyone looking at the code that that variable is a class variable and is inside of this class (as apposed to the superclass).  It distinguishes between variables that are either passed into a function or created locally inside that function with those created for the class.

**Comment by dionlarson** [comment]
I think this is something to be pointed out in recap sessions for Swift and the tutorials.
