### ISSUE TITLE
5 Tip it Up: Instructions leading up to adding code connections

### ISSUE THREAD

**Issue by szilardinho** [MakeSchool-Tutorials/Tip-Calculator-Swift#28]
The instructions begin with:

_"1. Control-click (or right-click) drag from bill amount label to under the class ViewController line and call the field billAmountField.
2. Control-click (or right-click) drag from the % selector and call the field tipSelector..."_

The video begins with the assistant editor  already in view, but perhaps it would be beneficial to begin the instructions with:

_"1. Open the assistant editor view and select the ViewController class so it is side by side with the main storyboard..."_

Reason:
Students may be unsure how to open the assistant editor, and/or their assistant editor might display the preview, another view controller, two main storyboards, etc instead of the proper ViewController

**Comment by dionlarson** [comment]
Reshot all videos with new constraints (using stackview). Rewrite coming soon.
