### ISSUE TITLE
Consider Simplifying UI with a Button

### ISSUE THREAD

**Issue by danielhaaser** [MakeSchool-Tutorials/Tip-Calculator-Swift#31]
There's a lot of complexity around hooking up the `updateTip()` function to three different things in the interface. This is a pretty uncommon situation, and it's probably not beneficial to show students how to do that at this time.  Instead, we can just add a "Calculate Tip" button which can be the one trigger to update everything. Doing that should cut down on the length of the tutorial.

**Comment by dionlarson** [comment]
Changed to button in rewrite.

Reshot all videos with new constraints (using stackview). Rewrite coming soon.
