### ISSUE TITLE
Unclear Size Inspector Section

### ISSUE THREAD

**Issue by cliffweitzman** [MakeSchool-Tutorials/Tip-Calculator-Swift#33]
![image](https://cloud.githubusercontent.com/assets/3460171/15981414/d5375e22-2f29-11e6-8785-5ef8847aff2a.png)

change one to start with the words 1. To do this, close the...
without this intro, I already changed the colors as instructed and then was confused when I got to this section since I thought it was new instructions.
1. A student new to Xcode would not know what the size inspector is let alone where it is, a photo with an color highlight of the size inspector would be useful here. 
   ![image](https://cloud.githubusercontent.com/assets/3460171/15981437/391a72a8-2f2a-11e6-99dc-da526105805c.png)

This is confusing - please rephrase.

**Comment by dionlarson** [comment]
Reshot all videos with new constraints (using stackview). Rewrite coming soon.
