### ISSUE TITLE
P6 TextField does not conform to TextFieldDelegate 

### ISSUE THREAD

**Issue by danstepanov** [MakeSchool-Tutorials/Tip-Calculator-Swift#36]
Within the textField connection, 
    `billAmountField.delegate = self`
was left out in the tutorial. Additionally,
the view controller must conform to:
    `UITextFieldDelegate` 
within the class declaration.

See **Changing the Keyboard**

**Comment by danielhaaser** [comment]
It turns out that it's not necessary to be a `UITextFieldDelegate` to have the keyboard pop up. I removed that bit from the tutorial.
